# Spring Boot 配置
server:
  port: 8081
  address: 0.0.0.0

dat:
  server:
    project-path: "."
    #variables:
    #  key1: "value1"
    #  key2: "value2"

logging:
  level:
    ai.dat: INFO
    org.springframework: WARN
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{20} - %msg%n"

spring:
  main:
    banner-mode: off
  jackson:
    default-property-inclusion: non_null
